### ISSUE TITLE
Request for Source Code

### ISSUE THREAD

**Issue by wnagyu-web** [wenzhengzeng/MPEblink#1]
Hello,

I am a research graduate student with a keen interest in the field of blink detection. After reading your paper, I became deeply interested in your research and intrigued by the methods and results presented.

I would like to further explore your work and apply it to my own research. Therefore, I wanted to inquire if it would be possible for you to share the source code of the method described in your paper. Having access to the code would greatly assist me in conducting relevant experiments and validations.

I understand that you may have your reasons for not publicly releasing the source code at this time. However, if you would be willing to share it with me, I would greatly appreciate it. I assure you that I will respect all relevant intellectual property and academic ethical guidelines. I will acknowledge your efforts and contributions appropriately in my work.

I am eager to engage in further discussion and would appreciate any guidance you can provide in obtaining the source code.

Thank you very much for your time and consideration.

Best regards,
Yours sincerely,
Yu Wang
[wang0624yu@163.com](mailto:wang0624yu@163.com)

**Comment by wenzhengzeng** [comment]
Hi,
Thanks for being interested in our work. I am currently busy with other projects and unable to organize and share the code you requested. However, I plan to make the code available after the CVPR conference. Thank you for your understanding！

**Comment by wenzhengzeng** [comment]
The code has been released.
