### ISSUE TITLE
How to make the MPEblink dataset 

### ISSUE THREAD

**Issue by mishimario** [wenzhengzeng/MPEblink#2]
Hi! I'm very impressed with your great work. And I'm very curious about how to make the MPEblink dataset.
1. How do you collect the source dataset? There is any public movie source?
2. Do you have code of making face bounding box? I'm very interested in how to use InsightFace and some tracking technique.
Thank you in advance!!

**Comment by wenzhengzeng** [comment]
Thank you for your interest in our work. You can find a variety of types of videos on the Internet (e.g., Archive.org, YouTube) and that is also the way that many works apply. Note that the data can only be used for research purposes and cannot be used for any commercial purposes.
For the second question, it is recommended to read [this](https://github.com/deepinsight/insightface/tree/master/python-package). The quick example in it is an easy-to-use example. After the function `app.get`, you can get the face bounding boxes, as well as the deep face features (for identification). In our annotation process, the tracking strategy considers both bounding box IoU (face position between adjacent frames should be similar) and the similarity of the deep face features (the similarity of face features from the same individual should be high across frames). Note that this strategy is not strong enough and much human efforts should be made to refine the detection & tracking results from the algorithm. I think you can also refer to some SOTA object tracking methods, which may have better performance.
