### ISSUE TITLE
how to run the demo

### ISSUE THREAD

**Issue by SuGuRuTaKaHaShi105** [wenzhengzeng/MPEblink#4]
I am a Japanese university student and I am impressed by your work. 

"Data preparation" has been completed. However, when I run "bash tools/code_for_demo/demo.sh" in the demo section, it asks for a pre-trained model. I downloaded "instblink_r50.pth" in the "Inference & Evaluation" section and tried to run the demo again, but it did not work. What is the problem?

**Comment by wenzhengzeng** [comment]
Thanks for your appreciation. Can you provide the specific error message?

**Comment by SuGuRuTaKaHaShi105** [comment]
<img width="1204" alt="スクリーンショット 2024-06-05 17 13 20" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/742806a0-150a-4210-87a9-aa9d7e0aaa1c">

**Comment by wenzhengzeng** [comment]
It seems that the path of the checkpoint file is not correct so the code can not find it. You should check "tools/code_for_demo/video_inference.py", line-22, and change it to the correct path on your side.

**Comment by SuGuRuTaKaHaShi105** [comment]
Thank you for the advice.
The first picture is the model directory. The second picture is the contents of the "tools/code_for_demo/video_inference.py" file, with the paths changed. The result is the same.

<img width="898" alt="スクリーンショット 2024-06-05 17 45 22" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/cfb16717-9cce-41e7-9b73-71c47f45513a">
<img width="1440" alt="スクリーンショット 2024-06-05 17 46 35" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/5d671a67-ed3c-454a-adb0-81b3e8a204fe">

**Comment by wenzhengzeng** [comment]
Normally, instblink_r50.pth is a file, not a directory. But in your case, it seems to be a directory because you can use the ls command.

**Comment by SuGuRuTaKaHaShi105** [comment]
I also thought that 'instblink_r50.pth' was a file, but when I downloaded it from Google Drive it was a directory.

**Comment by wenzhengzeng** [comment]
I just downloaded from [Google Drive](https://drive.google.com/file/d/1kRx_pPpOwAk9D6O3M5Ed7vyAqkZbCh83/view?usp=sharing) and it is a file. Maybe you can try again to see if the issue could be addressed.
![image](https://github.com/wenzhengzeng/MPEblink/assets/49069169/c4510ebc-b3f7-4caa-b236-b3441d150e72)

**Comment by SuGuRuTaKaHaShi105** [comment]
I've tried several times and it is a folder. The contents are a data folder, a date.pkl file, and a version file.

**Comment by SuGuRuTaKaHaShi105** [comment]
<img width="1439" alt="スクリーンショット 2024-06-07 14 28 36" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/77be20a5-d1ee-4e18-963c-4289ad825963">
<img width="1440" alt="スクリーンショット 2024-06-07 14 28 25" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/73fbf3ed-236f-47be-8c64-67517a29c4ff">
<img width="1440" alt="スクリーンショット 2024-06-07 14 27 55" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/700e7051-0ed3-4cc0-9316-95a94cc1e694">
<img width="1440" alt="スクリーンショット 2024-06-07 14 27 18" src="https://github.com/wenzhengzeng/MPEblink/assets/66825116/77afbb70-25cd-40ad-b0b2-0ef1f2ee9a79">

**Comment by SuGuRuTaKaHaShi105** [comment]
What OS are you using?

**Comment by SuGuRuTaKaHaShi105** [comment]
When downloaded it becomes a directory.

**Comment by wenzhengzeng** [comment]
I downloaded using Windows. Does the "wget" command work for Linux?

**Comment by SuGuRuTaKaHaShi105** [comment]
I cannot "wget" command, because I cannot get URL.
Please tell me "wget" command. For example "wget https:// ~~~~~~".

**Comment by wenzhengzeng** [comment]
You can try:
```
wget https://drive.google.com/file/d/1kRx_pPpOwAk9D6O3M5Ed7vyAqkZbCh83/view?usp=sharing
```

**Comment by SuGuRuTaKaHaShi105** [comment]
Is this correct?

![スクリーンショット 2024-06-07 18 35 11](https://github.com/wenzhengzeng/MPEblink/assets/66825116/3e76170c-06c5-41c7-a656-b80e5a92e9ed)
![スクリーンショット 2024-06-07 18 35 56](https://github.com/wenzhengzeng/MPEblink/assets/66825116/646c6ef6-d65c-4368-bd05-94e7e60c0bcf)![スクリーンショット 2024-06-07 18 35 11]

**Comment by wenzhengzeng** [comment]
What about this?
```
wget https://drive.google.com/uc?export=download&id=1kRx_pPpOwAk9D6O3M5Ed7vyAqkZbCh83
```

**Comment by SuGuRuTaKaHaShi105** [comment]
error?
![スクリーンショット 2024-06-07 18 46 17](https://github.com/wenzhengzeng/MPEblink/assets/66825116/f7b0569f-9344-4651-b607-40e0337c1ea7)
![スクリーンショット 2024-06-07 18 46 48](https://github.com/wenzhengzeng/MPEblink/assets/66825116/fd0b804f-5372-4e19-b977-da4280b9edf8)

**Comment by wenzhengzeng** [comment]
Maybe it is because the file is a little bit large. Sorry, currently I have no means to check the exact command for downloading. The URL is correct. You can look on the Internet to see if there is a good solution.

**Comment by SuGuRuTaKaHaShi105** [comment]
The problem was that the file was large.
I split the file, reduced the size, and downloaded it successfully.

Thank  you so much. If there are any other problems, please advise.
